/*
 Navicat Premium Data Transfer

 Source Server         : Oracle
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : SAKIB

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 21/02/2022 11:39:52
*/


-- ----------------------------
-- Table structure for AUTH_GROUP
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_GROUP";
CREATE TABLE "SAKIB"."AUTH_GROUP" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74538".nextval NOT NULL,
  "NAME" NVARCHAR2(150) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTH_GROUP_PERMISSIONS
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS";
CREATE TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74542".nextval NOT NULL,
  "GROUP_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "PERMISSION_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTH_PERMISSION
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_PERMISSION";
CREATE TABLE "SAKIB"."AUTH_PERMISSION" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74535".nextval NOT NULL,
  "NAME" NVARCHAR2(255) VISIBLE,
  "CONTENT_TYPE_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CODENAME" NVARCHAR2(100) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTH_USER
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_USER";
CREATE TABLE "SAKIB"."AUTH_USER" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74545".nextval NOT NULL,
  "PASSWORD" NVARCHAR2(128) VISIBLE,
  "LAST_LOGIN" TIMESTAMP(6) VISIBLE,
  "IS_SUPERUSER" NUMBER(1,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(150) VISIBLE,
  "FIRST_NAME" NVARCHAR2(150) VISIBLE,
  "LAST_NAME" NVARCHAR2(150) VISIBLE,
  "EMAIL" NVARCHAR2(254) VISIBLE,
  "IS_STAFF" NUMBER(1,0) VISIBLE NOT NULL,
  "IS_ACTIVE" NUMBER(1,0) VISIBLE NOT NULL,
  "DATE_JOINED" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTH_USER_GROUPS
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_USER_GROUPS";
CREATE TABLE "SAKIB"."AUTH_USER_GROUPS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74549".nextval NOT NULL,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "GROUP_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTH_USER_USER_PERMISSIONS
-- ----------------------------
DROP TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS";
CREATE TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74552".nextval NOT NULL,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "PERMISSION_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BUA_WORKS
-- ----------------------------
DROP TABLE "SAKIB"."BUA_WORKS";
CREATE TABLE "SAKIB"."BUA_WORKS" (
  "Service_ID" NUMBER(38,0) VISIBLE NOT NULL,
  "BUA_ID" NUMBER(38,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BuaAccept
-- ----------------------------
DROP TABLE "SAKIB"."BuaAccept";
CREATE TABLE "SAKIB"."BuaAccept" (
  "RequestID" NUMBER(38,0) VISIBLE NOT NULL,
  "BuaID" NUMBER(38,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BuaServiceIssue
-- ----------------------------
DROP TABLE "SAKIB"."BuaServiceIssue";
CREATE TABLE "SAKIB"."BuaServiceIssue" (
  "ID" NUMBER VISIBLE NOT NULL,
  "BuaID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Customer
-- ----------------------------
DROP TABLE "SAKIB"."Customer";
CREATE TABLE "SAKIB"."Customer" (
  "First Name" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Last Name" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Phone Number" NUMBER(38,0) VISIBLE NOT NULL,
  "Email Address" VARCHAR2(255 BYTE) VISIBLE,
  "Latitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Longitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "password" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "ID" NUMBER(38,0) VISIBLE NOT NULL,
  "rating" FLOAT(126) VISIBLE DEFAULT -1
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CustomerTechIssue
-- ----------------------------
DROP TABLE "SAKIB"."CustomerTechIssue";
CREATE TABLE "SAKIB"."CustomerTechIssue" (
  "customerID" NUMBER VISIBLE NOT NULL,
  "ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DJANGO_ADMIN_LOG
-- ----------------------------
DROP TABLE "SAKIB"."DJANGO_ADMIN_LOG";
CREATE TABLE "SAKIB"."DJANGO_ADMIN_LOG" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74566".nextval NOT NULL,
  "ACTION_TIME" TIMESTAMP(6) VISIBLE NOT NULL,
  "OBJECT_ID" NCLOB VISIBLE,
  "OBJECT_REPR" NVARCHAR2(200) VISIBLE,
  "ACTION_FLAG" NUMBER(11,0) VISIBLE NOT NULL,
  "CHANGE_MESSAGE" NCLOB VISIBLE,
  "CONTENT_TYPE_ID" NUMBER(11,0) VISIBLE,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DJANGO_CONTENT_TYPE
-- ----------------------------
DROP TABLE "SAKIB"."DJANGO_CONTENT_TYPE";
CREATE TABLE "SAKIB"."DJANGO_CONTENT_TYPE" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74531".nextval NOT NULL,
  "APP_LABEL" NVARCHAR2(100) VISIBLE,
  "MODEL" NVARCHAR2(100) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DJANGO_MIGRATIONS
-- ----------------------------
DROP TABLE "SAKIB"."DJANGO_MIGRATIONS";
CREATE TABLE "SAKIB"."DJANGO_MIGRATIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "SAKIB"."ISEQ$$_74528".nextval NOT NULL,
  "APP" NVARCHAR2(255) VISIBLE,
  "NAME" NVARCHAR2(255) VISIBLE,
  "APPLIED" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DJANGO_SESSION
-- ----------------------------
DROP TABLE "SAKIB"."DJANGO_SESSION";
CREATE TABLE "SAKIB"."DJANGO_SESSION" (
  "SESSION_KEY" NVARCHAR2(40) VISIBLE NOT NULL,
  "SESSION_DATA" NCLOB VISIBLE,
  "EXPIRE_DATE" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Employee
-- ----------------------------
DROP TABLE "SAKIB"."Employee";
CREATE TABLE "SAKIB"."Employee" (
  "PhoneNumber" NUMBER(30,0) VISIBLE DEFAULT "SAKIB"."EMPLOYEESEQ"."NEXTVAL",
  "Email" VARCHAR2(255 BYTE) VISIBLE,
  "FirstName" VARCHAR2(255 BYTE) VISIBLE,
  "LastName" VARCHAR2(255 BYTE) VISIBLE,
  "Latitude" VARCHAR2(255 BYTE) VISIBLE,
  "Longitude" VARCHAR2(255 BYTE) VISIBLE,
  "position" VARCHAR2(255 BYTE) VISIBLE,
  "hireDate" DATE VISIBLE,
  "ID" NUMBER(30,0) VISIBLE NOT NULL,
  "password" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EmployeeServRelation
-- ----------------------------
DROP TABLE "SAKIB"."EmployeeServRelation";
CREATE TABLE "SAKIB"."EmployeeServRelation" (
  "employeeID" NUMBER VISIBLE NOT NULL,
  "serviceID" NUMBER VISIBLE NOT NULL,
  "solved" NUMBER VISIBLE DEFAULT 0
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EmployeeTechRelation
-- ----------------------------
DROP TABLE "SAKIB"."EmployeeTechRelation";
CREATE TABLE "SAKIB"."EmployeeTechRelation" (
  "EmployeeID" NUMBER VISIBLE NOT NULL,
  "IssueID" NUMBER VISIBLE NOT NULL,
  "solved" NUMBER VISIBLE DEFAULT 0
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Payment Method
-- ----------------------------
DROP TABLE "SAKIB"."Payment Method";
CREATE TABLE "SAKIB"."Payment Method" (
  "ID" NUMBER VISIBLE NOT NULL,
  "Description" VARCHAR2(255 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Required Services
-- ----------------------------
DROP TABLE "SAKIB"."Required Services";
CREATE TABLE "SAKIB"."Required Services" (
  "transaction ID" NUMBER VISIBLE NOT NULL,
  "service ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Service
-- ----------------------------
DROP TABLE "SAKIB"."Service";
CREATE TABLE "SAKIB"."Service" (
  "Service_ID" NUMBER VISIBLE NOT NULL,
  "Description" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Name" VARCHAR2(255 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ServiceIssue
-- ----------------------------
DROP TABLE "SAKIB"."ServiceIssue";
CREATE TABLE "SAKIB"."ServiceIssue" (
  "ID" NUMBER VISIBLE NOT NULL,
  "serviceID" NUMBER VISIBLE,
  "Description" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Service_Provider
-- ----------------------------
DROP TABLE "SAKIB"."Service_Provider";
CREATE TABLE "SAKIB"."Service_Provider" (
  "PhoneNumber" NUMBER(38,0) VISIBLE NOT NULL,
  "FirstName" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "LastName" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Password" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "ID" NUMBER(38,0) VISIBLE DEFAULT "SAKIB"."CUSTOMERID_SEQ"."NEXTVAL" NOT NULL,
  "Latitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Longitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Gender" VARCHAR2(255 BYTE) VISIBLE DEFAULT 'Not',
  "Rating" FLOAT(10) VISIBLE DEFAULT -1 NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for Transaction
-- ----------------------------
DROP TABLE "SAKIB"."Transaction";
CREATE TABLE "SAKIB"."Transaction" (
  "Customer_ID" NUMBER(38,0) VISIBLE NOT NULL,
  "ServiceProvider_ID" NUMBER(38,0) VISIBLE,
  "payment Method" NUMBER(10,0) VISIBLE,
  "Amount" NUMBER(20,0) VISIBLE NOT NULL,
  "ID" NUMBER(38,0) VISIBLE NOT NULL,
  "time" DATE VISIBLE NOT NULL,
  "Latitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Longitude" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "Hire_Date" DATE VISIBLE,
  "Completed" VARCHAR2(255 BYTE) VISIBLE,
  "buaRating" FLOAT(126) VISIBLE DEFAULT -1,
  "customerRating" FLOAT(126) VISIBLE DEFAULT -1
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for buaTechIssue
-- ----------------------------
DROP TABLE "SAKIB"."buaTechIssue";
CREATE TABLE "SAKIB"."buaTechIssue" (
  "buaID" NUMBER VISIBLE NOT NULL,
  "ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for customerServiceIssue
-- ----------------------------
DROP TABLE "SAKIB"."customerServiceIssue";
CREATE TABLE "SAKIB"."customerServiceIssue" (
  "CustomerID" NUMBER VISIBLE NOT NULL,
  "ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for techIssue
-- ----------------------------
DROP TABLE "SAKIB"."techIssue";
CREATE TABLE "SAKIB"."techIssue" (
  "ID" NUMBER(30,0) VISIBLE NOT NULL,
  "Description" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Function structure for BUARATINGUPDATE
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SAKIB"."BUARATINGUPDATE" AS
BEGIN
 UPDATE "Transaction" SET "buaRating" =rat WHERE ID=trans;
 UPDATE "Service_Provider" SET "Rating"=rat WHERE ID=bua;
END;
/

-- ----------------------------
-- Function structure for CUSTOMERRATINGUPDATE
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SAKIB"."CUSTOMERRATINGUPDATE" AS
BEGIN
 UPDATE "Transaction" SET "customerRating" =rat WHERE ID=trans;
 UPDATE "Customer" SET "rating"=rat WHERE ID=bua;
END;
/

-- ----------------------------
-- Function structure for GETCUSTOMERNAME
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SAKIB"."GETCUSTOMERNAME" AS
BEGIN
 SELECT "First Name"||' '||"Last Name" INTO Name FROM "Customer" WHERE ID=IDinput;
 return Name;
END;
/

-- ----------------------------
-- Function structure for GETEMPLOYEEFORSERV
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SAKIB"."GETEMPLOYEEFORSERV" AS
BEGIN
SELECT COUNT(*) INTO cnt FROM "EmployeeServRelation" ;
FOR e in (SELECT * FROM "Employee")
LOOP
	SELECT COUNT(*) INTO tempCnt FROM "EmployeeServRelation" WHERE "employeeID"=e.ID;
	IF cnt >= tempCnt THEN
		emp := e.ID; 
	END IF;
	return emp;
END LOOP;
END ;
/

-- ----------------------------
-- Function structure for GETEMPLOYEEFORTECH
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SAKIB"."GETEMPLOYEEFORTECH" AS
BEGIN
SELECT COUNT(*) INTO cnt FROM "EmployeeTechRelation";
FOR e in (SELECT * FROM "Employee")
LOOP
	SELECT COUNT(*) INTO tempCnt FROM "EmployeeTechRelation" WHERE "EmployeeID"=e.ID;
	IF cnt >= tempCnt THEN
		emp := e.ID; 
	END IF;
	return emp;
END LOOP;
-- INSERT INTO "EmployeeTechRelation" VALUES(emp,:NEW.ID);
END ;
/

-- ----------------------------
-- Function structure for IS_NUMBER
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SAKIB"."IS_NUMBER" AS
BEGIN
	conv:=TO_NUMBER(numb)
	return 'YeS'
END

EXCEPTION
	WHERE VALUE_ERROR THEN
	return 'No'
/

-- ----------------------------
-- Function structure for RATING_FUNCTION
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SAKIB"."RATING_FUNCTION" AS
BEGIN
IF RATING>=0 THEN
   RETURN RATING;
ELSE
	RETURN 'NEW MEMBER';
END IF;

END;
/

-- ----------------------------
-- Function structure for UPDATE_BUAWORK
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SAKIB"."UPDATE_BUAWORK" AS
BEGIN
DELETE BUA_WORKS WHERE BUA_ID=buaID;
COMMIT;
-- FOR p IN para.FIRST..para.LAST 
-- 	LOOP
-- 		INSERT INTO BUA_WORKS VALUES(PARA(P),BUAID);
-- 	END LOOP;
DBMS_OUTPUT.PUT_LINE( 'UPADTE WAS SUCCESSFUL');
END UPDATE_buaWork;
/

-- ----------------------------
-- Function structure for WORK_COMPLTED
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SAKIB"."WORK_COMPLTED" AS
BEGIN
 FOR T IN (SELECT * FROM "Transaction" )
 LOOP
	

	IF MONTHS_BETWEEN(SYSDATE,T."Hire_Date")>0 THEN
		UPDATE "Transaction" SET "Completed"=1 WHERE ID=T.ID;
		COMMIT;
	END IF; 
END LOOP;

END;
/

-- ----------------------------
-- Sequence structure for CUSTOMERID_SEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."CUSTOMERID_SEQ";
CREATE SEQUENCE "SAKIB"."CUSTOMERID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for CUSTOMERSEQUENCE
-- ----------------------------
DROP SEQUENCE "SAKIB"."CUSTOMERSEQUENCE";
CREATE SEQUENCE "SAKIB"."CUSTOMERSEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for CUTOMERIDNEXT
-- ----------------------------
DROP SEQUENCE "SAKIB"."CUTOMERIDNEXT";
CREATE SEQUENCE "SAKIB"."CUTOMERIDNEXT" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for EMPLOYEESEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."EMPLOYEESEQ";
CREATE SEQUENCE "SAKIB"."EMPLOYEESEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74528
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74528";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74528" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74531
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74531";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74531" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74535
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74535";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74535" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74538
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74538";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74538" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74542
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74542";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74542" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74545
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74545";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74545" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74549
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74549";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74549" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74552
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74552";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74552" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_74566
-- ----------------------------
DROP SEQUENCE "SAKIB"."ISEQ$$_74566";
CREATE SEQUENCE "SAKIB"."ISEQ$$_74566" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for REQUSETID_SEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."REQUSETID_SEQ";
CREATE SEQUENCE "SAKIB"."REQUSETID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for SERVICEISSUESEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."SERVICEISSUESEQ";
CREATE SEQUENCE "SAKIB"."SERVICEISSUESEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for TECHISSUE
-- ----------------------------
DROP SEQUENCE "SAKIB"."TECHISSUE";
CREATE SEQUENCE "SAKIB"."TECHISSUE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for TECHISSUESEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."TECHISSUESEQ";
CREATE SEQUENCE "SAKIB"."TECHISSUESEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for TRANSACTIONTID_SEQ
-- ----------------------------
DROP SEQUENCE "SAKIB"."TRANSACTIONTID_SEQ";
CREATE SEQUENCE "SAKIB"."TRANSACTIONTID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP" ADD CONSTRAINT "SYS_C007605" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP" ADD CONSTRAINT "SYS_C007606" UNIQUE ("NAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP" ADD CONSTRAINT "SYS_C007604" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C007610" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID__0CD325B0_U" UNIQUE ("GROUP_ID", "PERMISSION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C007607" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C007608" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C007609" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
CREATE INDEX "SAKIB"."AUTH_GROUP_GROUP_ID_B120CBF9"
  ON "SAKIB"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SAKIB"."AUTH_GROUP_PERMISSION_84C5C92E"
  ON "SAKIB"."AUTH_GROUP_PERMISSIONS" ("PERMISSION_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C007603" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERM_CONTENT_T_01AB375A_U" UNIQUE ("CONTENT_TYPE_ID", "CODENAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C007601" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C007602" CHECK ("CONTENT_TYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_PERMISSION
-- ----------------------------
CREATE INDEX "SAKIB"."AUTH_PERMI_CONTENT_TY_2F476E4B"
  ON "SAKIB"."AUTH_PERMISSION" ("CONTENT_TYPE_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007620" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007621" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007611" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007613" CHECK ("IS_SUPERUSER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007614" CHECK ("IS_STAFF" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007615" CHECK ("IS_ACTIVE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007616" CHECK ("DATE_JOINED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007617" CHECK ("IS_SUPERUSER" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007618" CHECK ("IS_STAFF" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER" ADD CONSTRAINT "SYS_C007619" CHECK ("IS_ACTIVE" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C007625" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_G_94350C0C_U" UNIQUE ("USER_ID", "GROUP_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C007622" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C007623" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C007624" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_USER_GROUPS
-- ----------------------------
CREATE INDEX "SAKIB"."AUTH_USER__GROUP_ID_97559544"
  ON "SAKIB"."AUTH_USER_GROUPS" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SAKIB"."AUTH_USER__USER_ID_6A12ED8B"
  ON "SAKIB"."AUTH_USER_GROUPS" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C007629" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_P_14A6B632_U" UNIQUE ("USER_ID", "PERMISSION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C007626" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C007627" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C007628" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
CREATE INDEX "SAKIB"."AUTH_USER__PERMISSION_1FBB5F2C"
  ON "SAKIB"."AUTH_USER_USER_PERMISSIONS" ("PERMISSION_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SAKIB"."AUTH_USER__USER_ID_A95EAD1B"
  ON "SAKIB"."AUTH_USER_USER_PERMISSIONS" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table BUA_WORKS
-- ----------------------------
ALTER TABLE "SAKIB"."BUA_WORKS" ADD CONSTRAINT "SYS_C007768" PRIMARY KEY ("Service_ID", "BUA_ID");

-- ----------------------------
-- Checks structure for table BUA_WORKS
-- ----------------------------
ALTER TABLE "SAKIB"."BUA_WORKS" ADD CONSTRAINT "SYS_C007766" CHECK ("Service_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."BUA_WORKS" ADD CONSTRAINT "SYS_C007767" CHECK ("BUA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table BuaAccept
-- ----------------------------
ALTER TABLE "SAKIB"."BuaAccept" ADD CONSTRAINT "SYS_C007796" PRIMARY KEY ("RequestID", "BuaID");

-- ----------------------------
-- Checks structure for table BuaAccept
-- ----------------------------
ALTER TABLE "SAKIB"."BuaAccept" ADD CONSTRAINT "SYS_C007795" CHECK ("RequestID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table BuaServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."BuaServiceIssue" ADD CONSTRAINT "SYS_C007845" PRIMARY KEY ("ID", "BuaID");

-- ----------------------------
-- Checks structure for table BuaServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."BuaServiceIssue" ADD CONSTRAINT "SYS_C007843" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."BuaServiceIssue" ADD CONSTRAINT "SYS_C007844" CHECK ("BuaID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table Customer
-- ----------------------------
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007658" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table Customer
-- ----------------------------
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007652" CHECK ("First Name" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007653" CHECK ("Last Name" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007655" CHECK ("Phone Number" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007656" CHECK ("Latitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007657" CHECK ("Longitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Customer" ADD CONSTRAINT "SYS_C007748" CHECK ("password" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table Customer
-- ----------------------------
CREATE TRIGGER "SAKIB"."CUSTOMERRATING_UPDATE" BEFORE UPDATE ON "SAKIB"."Customer" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
cnt FLOAT(100);
BEGIN
SELECT COUNT(*) INTO cnt FROM "Transaction" WHERE "Customer_ID"  =:NEW.ID and "Completed" =1;
IF :OLD."rating" > -1 THEN
	:NEW."rating" := ( :NEW."rating" + :OLD."rating" ) / cnt;
END IF;
END;
/
CREATE TRIGGER "SAKIB"."CUSTOMERTRIGGER" BEFORE INSERT ON "SAKIB"."Customer" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.ID is null) 
DECLARE
  v_id "Customer".ID%TYPE;
BEGIN
  -- Select a new value from the sequence into a local variable. As David
  -- commented, this step is optional. You can directly select into :new.qname_id
  SELECT customerSequence.NEXTVAL INTO v_id FROM DUAL;
	DBMS_OUTPUT.PUT_LINE('SAKIB MADE THIS TRIGGER');
  -- :new references the record that you are about to insert into qname. Hence,
  -- you can overwrite the value of :new.qname_id (qname.qname_id) with the value
  -- obtained from your sequence, before inserting
  :new.ID := v_id;
END customerTrigger;
/

-- ----------------------------
-- Primary Key structure for table CustomerTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."CustomerTechIssue" ADD CONSTRAINT "SYS_C007814" PRIMARY KEY ("customerID", "ID");

-- ----------------------------
-- Checks structure for table CustomerTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."CustomerTechIssue" ADD CONSTRAINT "SYS_C007812" CHECK ("customerID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."CustomerTechIssue" ADD CONSTRAINT "SYS_C007813" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_ADMIN_LOG
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007646" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DJANGO_ADMIN_LOG
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007641" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007642" CHECK ("ACTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007643" CHECK ("ACTION_FLAG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007644" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C007645" CHECK ("ACTION_FLAG" >= 0) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table DJANGO_ADMIN_LOG
-- ----------------------------
CREATE INDEX "SAKIB"."DJANGO_ADM_CONTENT_TY_C4BCE8EB"
  ON "SAKIB"."DJANGO_ADMIN_LOG" ("CONTENT_TYPE_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SAKIB"."DJANGO_ADM_USER_ID_C564EBA6"
  ON "SAKIB"."DJANGO_ADMIN_LOG" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "SYS_C007599" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CO_APP_LABEL_76BD3D3B_U" UNIQUE ("APP_LABEL", "MODEL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "SYS_C007598" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_MIGRATIONS
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C007597" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DJANGO_MIGRATIONS
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C007595" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C007596" CHECK ("APPLIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_SESSION
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C007651" PRIMARY KEY ("SESSION_KEY");

-- ----------------------------
-- Checks structure for table DJANGO_SESSION
-- ----------------------------
ALTER TABLE "SAKIB"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C007649" CHECK ("SESSION_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C007650" CHECK ("EXPIRE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table DJANGO_SESSION
-- ----------------------------
CREATE INDEX "SAKIB"."DJANGO_SES_EXPIRE_DAT_A5C62663"
  ON "SAKIB"."DJANGO_SESSION" ("EXPIRE_DATE" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table Employee
-- ----------------------------
ALTER TABLE "SAKIB"."Employee" ADD CONSTRAINT "SYS_C007811" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table Employee
-- ----------------------------
ALTER TABLE "SAKIB"."Employee" ADD CONSTRAINT "SYS_C007810" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EmployeeServRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeServRelation" ADD CONSTRAINT "SYS_C007854" PRIMARY KEY ("employeeID", "serviceID");

-- ----------------------------
-- Checks structure for table EmployeeServRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeServRelation" ADD CONSTRAINT "SYS_C007852" CHECK ("employeeID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."EmployeeServRelation" ADD CONSTRAINT "SYS_C007853" CHECK ("serviceID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EmployeeTechRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeTechRelation" ADD CONSTRAINT "SYS_C007827" PRIMARY KEY ("EmployeeID", "IssueID");

-- ----------------------------
-- Checks structure for table EmployeeTechRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeTechRelation" ADD CONSTRAINT "SYS_C007825" CHECK ("EmployeeID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."EmployeeTechRelation" ADD CONSTRAINT "SYS_C007826" CHECK ("IssueID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table Payment Method
-- ----------------------------
ALTER TABLE "SAKIB"."Payment Method" ADD CONSTRAINT "SYS_C007683" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table Payment Method
-- ----------------------------
ALTER TABLE "SAKIB"."Payment Method" ADD CONSTRAINT "SYS_C007681" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Payment Method" ADD CONSTRAINT "SYS_C007682" CHECK ("Description" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table Required Services
-- ----------------------------
ALTER TABLE "SAKIB"."Required Services" ADD CONSTRAINT "SYS_C007696" PRIMARY KEY ("transaction ID", "service ID");

-- ----------------------------
-- Checks structure for table Required Services
-- ----------------------------
ALTER TABLE "SAKIB"."Required Services" ADD CONSTRAINT "SYS_C007694" CHECK ("transaction ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Required Services" ADD CONSTRAINT "SYS_C007695" CHECK ("service ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table Service
-- ----------------------------
ALTER TABLE "SAKIB"."Service" ADD CONSTRAINT "SYS_C007661" PRIMARY KEY ("Service_ID");

-- ----------------------------
-- Checks structure for table Service
-- ----------------------------
ALTER TABLE "SAKIB"."Service" ADD CONSTRAINT "SYS_C007659" CHECK ("Service_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service" ADD CONSTRAINT "SYS_C007660" CHECK ("Description" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service" ADD CONSTRAINT "SYS_C007765" CHECK ("Name" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."ServiceIssue" ADD CONSTRAINT "SYS_C007823" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."ServiceIssue" ADD CONSTRAINT "SYS_C007822" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table Service_Provider
-- ----------------------------
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007764" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table Service_Provider
-- ----------------------------
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007758" CHECK ("PhoneNumber" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007759" CHECK ("FirstName" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007760" CHECK ("LastName" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007762" CHECK ("Password" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007763" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007786" CHECK ("Latitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007787" CHECK ("Longitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Service_Provider" ADD CONSTRAINT "SYS_C007789" CHECK ("Rating" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table Service_Provider
-- ----------------------------
CREATE TRIGGER "SAKIB"."RATING_UPDATE" BEFORE UPDATE ON "SAKIB"."Service_Provider" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
cnt FLOAT(100);
BEGIN
SELECT COUNT(*) INTO cnt FROM "Transaction" WHERE "ServiceProvider_ID"  =:NEW.ID and "Completed" =1;
IF :OLD."Rating" > -1 THEN
	:NEW."Rating" := ( :NEW."Rating" + :OLD."Rating" ) / cnt;
END IF;
END;
/

-- ----------------------------
-- Primary Key structure for table Transaction
-- ----------------------------
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007675" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table Transaction
-- ----------------------------
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007673" CHECK ("Customer_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007691" CHECK ("Amount" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007692" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007805" CHECK ("time" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007806" CHECK ("Latitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "SYS_C007807" CHECK ("Longitude" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table Transaction
-- ----------------------------
CREATE TRIGGER "SAKIB"."TRANSACTIONTRIGGER" BEFORE INSERT ON "SAKIB"."Transaction" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN ( new.ID IS NULL) 
DECLARE
  v_id "Transaction".ID%TYPE;
	lat  "Transaction"."Latitude"%TYPE;
	lng "Transaction"."Longitude"%TYPE;
BEGIN
  -- Select a new value from the sequence into a local variable. As David
  -- commented, this step is optional. You can directly select into :new.qname_id
  SELECT transactiontID_seq.NEXTVAL INTO v_id FROM DUAL;
	DBMS_OUTPUT.PUT_LINE('SAKIB MADE THIS TRIGGER FOR REQUEST');
  -- :new references the record that you are about to insert into qname. Hence,
  -- you can overwrite the value of :new.qname_id (qname.qname_id) with the value
  -- obtained from your sequence, before inserting
	SELECT "Latitude" INTO lat  from "Customer" WHERE ID=:new."Customer_ID";
	SELECT  "Longitude" INTO lng  from "Customer" WHERE ID=:new."Customer_ID";
	:new."Longitude":=lng;
	:new."Latitude":=lat;
  :new.ID := v_id;
-- 	:new."time":=SYSDATE;
END transactionTrigger;
/

-- ----------------------------
-- Primary Key structure for table buaTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."buaTechIssue" ADD CONSTRAINT "SYS_C007819" PRIMARY KEY ("buaID", "ID");

-- ----------------------------
-- Checks structure for table buaTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."buaTechIssue" ADD CONSTRAINT "SYS_C007817" CHECK ("buaID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."buaTechIssue" ADD CONSTRAINT "SYS_C007818" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table customerServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."customerServiceIssue" ADD CONSTRAINT "SYS_C007840" PRIMARY KEY ("CustomerID", "ID");

-- ----------------------------
-- Checks structure for table customerServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."customerServiceIssue" ADD CONSTRAINT "SYS_C007838" CHECK ("CustomerID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."customerServiceIssue" ADD CONSTRAINT "SYS_C007839" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table techIssue
-- ----------------------------
ALTER TABLE "SAKIB"."techIssue" ADD CONSTRAINT "SYS_C007809" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table techIssue
-- ----------------------------
ALTER TABLE "SAKIB"."techIssue" ADD CONSTRAINT "SYS_C007808" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_PERMISSION
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_USER_GROUPS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table BUA_WORKS
-- ----------------------------
ALTER TABLE "SAKIB"."BUA_WORKS" ADD CONSTRAINT "pointBua" FOREIGN KEY ("BUA_ID") REFERENCES "SAKIB"."Service_Provider" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."BUA_WORKS" ADD CONSTRAINT "pointService" FOREIGN KEY ("Service_ID") REFERENCES "SAKIB"."Service" ("Service_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table BuaAccept
-- ----------------------------
ALTER TABLE "SAKIB"."BuaAccept" ADD CONSTRAINT "buaFor" FOREIGN KEY ("BuaID") REFERENCES "SAKIB"."Service_Provider" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."BuaAccept" ADD CONSTRAINT "requestFor" FOREIGN KEY ("RequestID") REFERENCES "SAKIB"."Transaction" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table BuaServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."BuaServiceIssue" ADD CONSTRAINT "buaREF" FOREIGN KEY ("BuaID") REFERENCES "SAKIB"."Service_Provider" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."BuaServiceIssue" ADD CONSTRAINT "serviceId" FOREIGN KEY ("ID") REFERENCES "SAKIB"."ServiceIssue" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CustomerTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."CustomerTechIssue" ADD CONSTRAINT "customer" FOREIGN KEY ("customerID") REFERENCES "SAKIB"."Customer" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."CustomerTechIssue" ADD CONSTRAINT "techIssue" FOREIGN KEY ("ID") REFERENCES "SAKIB"."techIssue" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table DJANGO_ADMIN_LOG
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table EmployeeServRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeServRelation" ADD CONSTRAINT "IDref2" FOREIGN KEY ("serviceID") REFERENCES "SAKIB"."ServiceIssue" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."EmployeeServRelation" ADD CONSTRAINT "employeeRef" FOREIGN KEY ("employeeID") REFERENCES "SAKIB"."Employee" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EmployeeTechRelation
-- ----------------------------
ALTER TABLE "SAKIB"."EmployeeTechRelation" ADD CONSTRAINT "employee" FOREIGN KEY ("EmployeeID") REFERENCES "SAKIB"."Employee" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."EmployeeTechRelation" ADD CONSTRAINT "issue" FOREIGN KEY ("IssueID") REFERENCES "SAKIB"."techIssue" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table Required Services
-- ----------------------------
ALTER TABLE "SAKIB"."Required Services" ADD CONSTRAINT "service ID" FOREIGN KEY ("service ID") REFERENCES "SAKIB"."Service" ("Service_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Required Services" ADD CONSTRAINT "transaction id" FOREIGN KEY ("transaction ID") REFERENCES "SAKIB"."Transaction" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."ServiceIssue" ADD CONSTRAINT "service" FOREIGN KEY ("serviceID") REFERENCES "SAKIB"."Transaction" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table Transaction
-- ----------------------------
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "buaId" FOREIGN KEY ("ServiceProvider_ID") REFERENCES "SAKIB"."Service_Provider" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "customerID" FOREIGN KEY ("Customer_ID") REFERENCES "SAKIB"."Customer" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."Transaction" ADD CONSTRAINT "paymentMethod" FOREIGN KEY ("payment Method") REFERENCES "SAKIB"."Payment Method" ("ID") ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table buaTechIssue
-- ----------------------------
ALTER TABLE "SAKIB"."buaTechIssue" ADD CONSTRAINT "BUA" FOREIGN KEY ("buaID") REFERENCES "SAKIB"."Service_Provider" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."buaTechIssue" ADD CONSTRAINT "ID" FOREIGN KEY ("ID") REFERENCES "SAKIB"."techIssue" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table customerServiceIssue
-- ----------------------------
ALTER TABLE "SAKIB"."customerServiceIssue" ADD CONSTRAINT "CUSTOMER" FOREIGN KEY ("CustomerID") REFERENCES "SAKIB"."Customer" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SAKIB"."customerServiceIssue" ADD CONSTRAINT "IDref" FOREIGN KEY ("ID") REFERENCES "SAKIB"."ServiceIssue" ("ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
